version: "3.1"
services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkinsdata:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
volumes:
  jenkinsdata:
    driver: local
