# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
